### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by landhell** [fwilleke80/FlockModifier#6]
the plugin is totally awesome, it really useful and easy to use, however, i wonder if orientation or up vector kinda feature is reasonable to add-on?

as you can see the image i attached, some fishes are off their orientation after few turns, this is obvious when come to certain amount of closeup, thank you for looking into it.

![flockmodifier_request](https://user-images.githubusercontent.com/315618/32934995-ffe16902-cba8-11e7-9992-26ffe87b8328.jpg)

**Comment by fwilleke80** [comment]
Hi,
Yeah, that's a common request. Unfortunately, the standard C4D particle system only stores a position and velocity per particle, and no alignment matrix. That's calculated internally only by the Particle Emitter object that generates the particles' geometry. Therefore, I have no way of fixing that issue.
Cheers,
Frank

**Comment by landhell** [comment]
i see.. pity then.. what about thinking particle? does thinking particle stores more information? is your plugin possible to tweak for it? or do you have anyway to setup with xpresso?

**Comment by fwilleke80** [comment]
For TP, it has to be a node plugin, including all the ballast and inefficiency that comes with XPresso and TP in C4D.
